<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hip Chat Integration Endpoints</title>
    <meta name="description" content="Endpoints for Custom Hipchat Integrations.">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/cyborg/bootstrap.min.css" rel="stylesheet"></head>
<body>
    <div class="site-wrapper">
        <h1>Jam Cart.</h1>
        <p>HipChat endpoint: <a href="{{ ngrokUrl }}/bot">{{ ngrokUrl }}/bot</a></p>
    </div>
</body>
